- set_fact:
   image_upload_spec:
    spec:
      name: "ansible_centos"
      resources:
        image_type: "DISK_IMAGE"
        source_uri: "{{ nat_vars.centos_image_url }}"
        source_options:
          allow_insecure_connection: true
      description: "Uploaded via ansible playbook for nat routing"
    metadata:
      kind: "image"

- name: Download Centos Image
  import_tasks:
   file: "../../common_tasks/submit_task_v3api.yaml"
  vars:
   endpoint_ip: "{{ pc_ip }}"
   endpoint_api_path: "api/nutanix/v3/images"
   endpoint_api_method: "POST"
   endpoint_api_body: '{{ image_upload_spec | to_json }}'
   endpoint_api_task: "api/nutanix/v3/images"
   endpoint_api_password: "{{ pc_password }}"
   endpoint_api_username: "admin"
