- name: Centos Image Import
  import_tasks:
   file: "image_import.yml"

- name: PVNet Create
  import_tasks:
   file: "pv_net_create.yml"


- name: Nat_VM_create
  import_tasks:
   file: "nat_vm_create.yml"


##the main playbook will then call nat_vm_configure after changing host to the nat vmadm


