- set_fact:
   vm_deploy_spec:
    spec:
      description: string
      resources:
        num_threads_per_core: 1
        num_vcpus_per_socket: 2
        num_sockets: 2
        memory_size_mib: 4000
        disk_list:
        - device_properties:
            device_type: DISK
          data_source_reference:
            is_direct_attach: true
            kind: image
            uuid: "{{ centos_image_uuid }}"
            name: "ansible_centos"
        nic_list:
        - ip_endpoint_list:
          - ip_type: "dhcp"
          subnet_reference:
            kind: subnet
            name: string
            uuid: string (UUID)
          model: string
          is_connected: true
          trunked_vlan_list:
          - 123
        guest_os_id: string
        serial_port_list:
        - index: 123
          is_connected: true
        is_agent_vm: true
        guest_tools:
          nutanix_guest_tools:
            state: string
            version: string
            ngt_state: string
            credentials:
              username: string
              password: string
            iso_mount_state: string
            enabled_capability_list:
            - string
        vga_console_enabled: true
        power_state: string
        disable_branding: true
      cluster_reference:
        kind: cluster
        name: string
        uuid: string (UUID)
      name: string
      availability_zone_reference:
        kind: availability_zone
        name: string
        uuid: string (UUID)
    api_version: 3.1.0
    metadata:
      last_update_time: string (date-time)
      use_categories_mapping: false
      kind: vm
      uuid: string (UUID)
      project_reference:
        kind: project
        name: string
        uuid: string (UUID)
      spec_version: 123
      creation_time: string (date-time)
      spec_hash: string
      categories_mapping: {}
      should_force_translate: true
      owner_reference:
        kind: user
        name: string
        uuid: string (UUID)
      categories: {}
      name: string