- set_fact:
   pv_network: "{{nat_vars.pv_net_details.network}}/{{nat_vars.pv_net_details.netmask}}"

- debug:
   var: pv_network

- set_fact:
   pv_network_prefix: "{{ pv_network | ipaddr('prefix')}}"

- debug:
   var: pv_network_prefix

- set_fact:
   network_create_spec:
    ip_config:
      default_gateway: "{{nat_vars.pv_net_details.gateway}}"
      network_address: "{{nat_vars.pv_net_details.network}}"
      dhcp_options:
       domain_name_servers: "{{nat_vars.pv_net_details.dns}}"
      pool:
      - range: "{{nat_vars.pv_net_details.range}}"
      prefix_length: "{{pv_network_prefix | int }}"
    name: "{{nat_vars.pv_net_details.name}}"
    network_type: EXTERNAL
    vlan_id: "{{nat_vars.pv_net_details.vlan}}"


- name: Create ansible private network network
  uri:
   url: https://{{ ansible_host }}:9440/api/nutanix/v2.0/networks
   url_username: "{{ api_username }}"
   url_password: "{{ pe_password }}"
   validate_certs: false
   force_basic_auth: true
   return_content: true
   body_format: json
   method: "POST"
   body: "{{ network_create_spec | to_json }}"
   follow_redirects: all
   status_code: [200,201,202]
  debugger: on_failed
  register: pv_network_create_status


- set_fact:
   pv_net_uuid: "{{ pv_network_create_status.json.network_uuid }}"

- debug: 
   msg: network created with {{ pv_net_uuid }}
