
# - name: enable karbon service
#   uri: 
#    url: https://{{ pc_ip }}:9440/PrismGateway/services/rest/v1/genesis
#    url_username: "admin"
#    url_password: "{{ pc_password }}"
#    validate_certs: false
#    force_basic_auth: true
#    return_content: true
#    body_format: json
#    method: "POST"
#    body: '{"value":"{\".oid\":\"ClusterManager\",\".method\":\"enable_service_with_prechecks\",\".kwargs\":{\"service_list_json\":\"{\\\"service_list\\\":[\\\"KarbonUIService\\\",\\\"KarbonCoreService\\\"]}\"}}"}'
#    follow_redirects: all
#    status_code: [200,202]
#   debugger: on_failed
#   register: task_status

# Below api call does not work
#- name: check karbon service
#   uri:
#     url: https://{{ pc_ip }}:9440/karbon/version
#     url_username: "admin"
#     url_password: "SREs4eva!"
#     validate_certs: false
#     force_basic_auth: true
#     return_content: true
#     body_format: json
#     method: "GET"
#     follow_redirects: all
#     status_code: [200,202]
#   debugger: on_failed
#   register: task_status
